title: "Tổng hợp kiến thức 📚"

theme: just-the-docs

url: https://your-username.github.io

# Math (giữ lại)
markdown: kramdown
kramdown:
  math_engine: mathjax

# Gợi ý thêm
color_scheme: dark
search_enabled: true
